### PR TITLE
Fixed aux buttons for Veikk A30 V2

### LINKED ISSUE #1854: VEIKK A50 does not have working aux buttons
## Description
VEIKK A50 currently uses `SkipByteTabletReportParser` which does not implement aux buttons. The ReportParser used should be changed to something that does.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Any
| OpenTabletDriver Version | d758023183600
| Tablet                   | VEIKK A50

### PR DESCRIPTION
**Pull request by Julian-Sz**
@jamesbt365 said in this PR https://github.com/OpenTabletDriver/OpenTabletDriver/pull/2216 that the aux buttons might not be working due to the OEM drivers still being installed, but that's not the case (they are also broken on a fresh windows 10 install). 

I reverse-engineered the OEM driver and it turns out the tablet needs 3 initial reports (one for the digitizer, one for the aux buttons, one for the touchpad). I've added a parser that can parse the aux button reports. I don't know if that solution works for other Veikk tablets as well, it might fix #1854.

### CODE REVIEW

File: OpenTabletDriver.Configurations/Parsers/Veikk/VeikkAuxReport.cs [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+namespace OpenTabletDriver.Configurations.Parsers.Veikk
+{
+    public struct VeikkAuxReport : IAuxReport
+    {
+        public VeikkAuxReport(byte[] report)
+        {
+            Raw = report;
+            AuxButtons = new bool[]
+            {
+                report[4] == 1 && report[3].IsBitSet(0), // First
```
Comment (X9VoiD) [inline OpenTabletDriver.Configurations/Parsers/Veikk/VeikkAuxReport.cs:12]: `report[4].IsBitSet(0)` etc etc.

**Review by X9VoiD — CHANGES_REQUESTED** [review]

**Review by X9VoiD — APPROVED** [review]
If a VEIKK tablet has more than 4 buttons then we can just extend this code.
